### ISSUE TITLE
EcsRendering example unresolved external symbol

### ISSUE THREAD

**Issue by earjuice** [Hperigo/Cinder-ecs#2]
Hey, getting unresolved external symbol om ecs::IDrawable when trying to run the rendering example...  vs2015 build

**Comment by earjuice** [comment]
my bad... it's in the Todo list.  Great block minus the windows sample!  Been learning about Ecs and this really helps break down the concept... great read.

**Comment by Hperigo** [comment]
Hi! thanks! sorry for the delay seeing this, I was a bit away from the computer these days and honestly I haven't touched this version of the library in some time. 

I've being working on a openframeworks version ( since it's currently what I'm using at work ), it relies on a separate repository: https://github.com/Hperigo/PerigoEcs
